"use client";
import { FormEvent, useEffect, useState } from "react";

declare global { interface Window { shopify?: { idToken(): Promise<string>; toast?: { show(message: string): void }; resourcePicker(options:Record<string,unknown>):Promise<any[]> } } }
type Rule={mode:"flat"|"live";standard:number;express:number;freeThreshold:number};
type RetailSettings={defaultRule:Rule;bulkyRule:Rule;states:Record<string,Rule>};
type Status = { ready:boolean; originPostcode:string; australiaPost:boolean; aramex:boolean; tnt:boolean; bulkyProducts:{id:string;title:string}[]; retailSettings:RetailSettings };
const baseRule:Rule={mode:"flat",standard:10,express:20,freeThreshold:100};
const stateCodes=["NSW","VIC","QLD","SA","WA","NT","TAS","ACT"];
const emptyStatus:Status={ready:false,originPostcode:"",australiaPost:false,aramex:false,tnt:false,bulkyProducts:[],retailSettings:{defaultRule:baseRule,bulkyRule:{...baseRule,mode:"live"},states:Object.fromEntries(stateCodes.map(s=>[s,{...baseRule,mode:s==="WA"||s==="NT"?"live":"flat"}]))}};

async function authenticatedFetch(path:string,init:RequestInit={}){
  if(!window.shopify) throw new Error("Open this dashboard from Shopify Admin.");
  const token=await window.shopify.idToken();
  return fetch(path,{...init,headers:{...init.headers,authorization:`Bearer ${token}`,"content-type":"application/json"}});
}

export default function Home(){
  const [status,setStatus]=useState<Status>(emptyStatus); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string|null>(null); const [testing,setTesting]=useState(false); const [notice,setNotice]=useState("");
  async function refresh(){setLoading(true);try{const r=await authenticatedFetch("/api/settings");const d=await r.json() as Status&{error?:string};if(!r.ok)throw new Error(d.error||"Unable to load settings");setStatus(d)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load settings")}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[]);
  async function save(event:FormEvent<HTMLFormElement>,carrier:string){event.preventDefault();const form=event.currentTarget;setSaving(carrier);setNotice("");const values=Object.fromEntries(new FormData(form));try{const r=await authenticatedFetch("/api/settings",{method:"POST",body:JSON.stringify({carrier,...values})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Unable to save");setNotice(`${carrier} settings saved. Live rates remain off until you enable them.`);window.shopify?.toast?.show(`${carrier} settings saved`);form.reset();await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Unable to save")}finally{setSaving(null)}}
  async function testAustraliaPost(){setTesting(true);setNotice("");try{const r=await authenticatedFetch("/api/test-carrier",{method:"POST",body:JSON.stringify({carrier:"Australia Post"})});const d=await r.json() as {message?:string;error?:string};if(!r.ok)throw new Error(d.error||"Connection test failed");setNotice(d.message||"Australia Post connection successful.");window.shopify?.toast?.show("Australia Post connection successful")}catch(e){setNotice(e instanceof Error?e.message:"Connection test failed")}finally{setTesting(false)}}
  async function connectShopify(){setTesting(true);setNotice("");try{const r=await authenticatedFetch("/api/connect-shopify",{method:"POST",body:"{}"});const d=await r.json() as {message?:string;error?:string};if(!r.ok)throw new Error(d.error||"Shopify connection failed");setNotice(d.message||"Connected to Shopify.");window.shopify?.toast?.show("Carrier service connected")}catch(e){setNotice(e instanceof Error?e.message:"Shopify connection failed")}finally{setTesting(false)}}
  async function selectBulkyProducts(){if(!window.shopify)return;const selected=await window.shopify.resourcePicker({type:"product",multiple:true,action:"select",selectionIds:status.bulkyProducts.map(p=>({id:p.id}))});if(!selected)return;setSaving("Bulky products");try{const products=selected.map((p:any)=>({id:p.id,title:p.title,variantIds:(p.variants||[]).map((v:any)=>v.id)}));const r=await authenticatedFetch("/api/settings",{method:"POST",body:JSON.stringify({carrier:"Bulky products",products})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Unable to save bulky products");setNotice("Bulky products saved. Retail orders containing them will use live Australia Post rates.");await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Unable to save bulky products")}finally{setSaving(null)}}
  async function saveRetailRules(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving("Retail rules");const data=new FormData(event.currentTarget);const read=(prefix:string):Rule=>({mode:String(data.get(`${prefix}_mode`)) as "flat"|"live",standard:Number(data.get(`${prefix}_standard`)),express:Number(data.get(`${prefix}_express`)),freeThreshold:Number(data.get(`${prefix}_free`))});const retailSettings:RetailSettings={defaultRule:read("default"),bulkyRule:read("bulky"),states:Object.fromEntries(stateCodes.map(s=>[s,read(s)]))};try{const r=await authenticatedFetch("/api/settings",{method:"POST",body:JSON.stringify({carrier:"Retail rules",retailSettings})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Unable to save Retail rules");setNotice("Retail shipping rules saved.");await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Unable to save Retail rules")}finally{setSaving(null)}}
  return <main className="shell">
    <header className="hero"><div><p className="eyebrow">Budget Salon Supplies</p><h1>Shipping dashboard</h1><p>Retail rules are fixed. Add carrier credentials when your accounts are ready.</p></div><span className={`pill ${status.ready?"good":"warn"}`}>{loading?"Checking…":status.ready?"Secure connection ready":"Secure setup required"}</span></header>
    {notice&&<div className="notice" role="status">{notice}</div>}
    <section className="rules"><article><strong>Retail</strong><span>$10 under $100</span></article><article><strong>Retail</strong><span>Free from $100</span></article><article><strong>Trade & Freelance</strong><span>Live carrier rates</span></article></section><button className="connectButton" disabled={!status.australiaPost||!status.originPostcode||testing} onClick={connectShopify}>{testing?"Connecting…":"Connect live rates to Shopify"}</button>
    <section className="card"><div className="cardTitle"><div><h2>Dispatch location</h2><p>Used as the origin for every carrier quote.</p></div><span>{status.originPostcode||"Not set"}</span></div><form onSubmit={e=>save(e,"Origin")} className="compactForm"><label>Australian postcode<input name="originPostcode" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="e.g. 2000" required/></label><button disabled={saving==="Origin"}>{saving==="Origin"?"Saving…":"Save postcode"}</button></form></section>
    <section className="card"><div className="cardTitle"><div><h2>Bulky Retail products</h2><p>Selected products use live Australia Post weight-based rates. All Retail orders to WA or NT also use live rates automatically.</p></div><span>{status.bulkyProducts.length} selected</span></div>{status.bulkyProducts.length>0&&<p>{status.bulkyProducts.map(p=>p.title).join(", ")}</p>}<button onClick={selectBulkyProducts} disabled={saving==="Bulky products"}>{saving==="Bulky products"?"Saving…":"Select Shopify products"}</button></section>
    <section className="card"><div className="cardTitle"><div><h2>Retail shipping prices</h2><p>Set Standard, Express and free-shipping thresholds. Choose Live for automatic carrier pricing.</p></div></div><form onSubmit={saveRetailRules} className="rulesForm"><RuleRow code="default" label="Default Retail" rule={status.retailSettings.defaultRule}/><RuleRow code="bulky" label="Selected bulky products" rule={status.retailSettings.bulkyRule}/>{stateCodes.map(code=><RuleRow key={code} code={code} label={code} rule={status.retailSettings.states[code]||baseRule}/>) }<button disabled={saving==="Retail rules"}>{saving==="Retail rules"?"Saving…":"Save Retail pricing"}</button></form></section>
    <div className="carrierGrid">
      <Carrier title="Australia Post" connected={status.australiaPost} onSave={e=>save(e,"Australia Post")} saving={saving==="Australia Post"}><label>API URL<input name="apiUrl" type="url" placeholder="https://digitalapi.auspost.com.au" required/></label><label>Username / API key<input name="username" autoComplete="off" required/></label><label>Password / API secret<input name="password" type="password" autoComplete="new-password" required/></label><label>Charge account number<input name="accountNumber" inputMode="numeric" placeholder="10 digits" required/></label><button type="button" className="secondary" disabled={!status.australiaPost||testing} onClick={testAustraliaPost}>{testing?"Testing…":"Test saved connection"}</button></Carrier>
      <Carrier title="Aramex" connected={status.aramex} onSave={e=>save(e,"Aramex")} saving={saving==="Aramex"}><label>Client name<input name="clientName" required/></label><label>Client ID<input name="clientId" autoComplete="off" required/></label><label>Description<input name="description" required/></label><label>Client secret<input name="clientSecret" type="password" autoComplete="new-password" required/></label></Carrier>
      <Carrier title="TNT / FedEx" connected={status.tnt} onSave={e=>save(e,"TNT")} saving={saving==="TNT"}><label>API URL<input name="apiUrl" type="url" placeholder="https://…" required/></label><label>API token<input name="apiToken" type="password" autoComplete="off" required/></label></Carrier>
    </div><p className="footnote">Credentials are encrypted before storage. Saving credentials does not turn live checkout rates on.</p>
  </main>
}
function Carrier({title,connected,saving,onSave,children}:{title:string;connected:boolean;saving:boolean;onSave(e:FormEvent<HTMLFormElement>):void;children:React.ReactNode}){return <section className="card carrier"><div className="cardTitle"><h2>{title}</h2><span className={`dot ${connected?"on":""}`}>{connected?"Saved":"Not connected"}</span></div><form onSubmit={onSave}>{children}<button disabled={saving}>{saving?"Saving…":"Save credentials"}</button></form></section>}
function RuleRow({code,label,rule}:{code:string;label:string;rule:Rule}){return <div className="ruleRow"><strong>{label}</strong><label>Pricing<select name={`${code}_mode`} defaultValue={rule.mode}><option value="flat">Custom prices</option><option value="live">Live carrier rate</option></select></label><label>Standard $<input name={`${code}_standard`} type="number" min="0" step="0.01" defaultValue={rule.standard}/></label><label>Express $<input name={`${code}_express`} type="number" min="0" step="0.01" defaultValue={rule.express}/></label><label>Free from $<input name={`${code}_free`} type="number" min="0" step="0.01" defaultValue={rule.freeThreshold}/></label></div>}
